Traceback (most recent call last):
  File "/home/hawkwood/.local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/molecule/command/test.py", line 159, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "/home/hawkwood/.local/lib/python3.9/site-packages/ansible_compat/runtime.py", line 245, in prepare_environment
    self.install_requirements("requirements.yml", retry=retry)
  File "/home/hawkwood/.local/lib/python3.9/site-packages/ansible_compat/runtime.py", line 217, in install_requirements
    raise AnsibleCommandError(run)
ansible_compat.errors.AnsibleCommandError: Got 1 exit code while running: ansible-galaxy role install -vr requirements.yml --roles-path /home/hawkwood/.cache/ansible-compat/466a94/roles
